# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x64)
  OSE_config = debug_x64
  Sandbox_config = debug_x64
endif
ifeq ($(config),release_x64)
  OSE_config = release_x64
  Sandbox_config = release_x64
endif

PROJECTS := OSE Sandbox

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

OSE:
ifneq (,$(OSE_config))
	@echo "==== Building OSE ($(OSE_config)) ===="
	@${MAKE} --no-print-directory -C OSE -f Makefile config=$(OSE_config)
endif

Sandbox:
ifneq (,$(Sandbox_config))
	@echo "==== Building Sandbox ($(Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C Sandbox -f Makefile config=$(Sandbox_config)
endif

clean:
	@${MAKE} --no-print-directory -C OSE -f Makefile clean
	@${MAKE} --no-print-directory -C Sandbox -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x64"
	@echo "  release_x64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   OSE"
	@echo "   Sandbox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"